### PR TITLE
Feature/pea 6917 loadmore graphql

### PR DESCRIPTION
**Pull request by tdang81**

### CODE REVIEW

**Comment by steve-junker** [comment]
Into master?

**Comment by tdang81** [comment]
@steve-junker develop seems to be outdated. @katallaxie can you confirm it?

**Comment by tdang81** [comment]
@katallaxie you mean `develop` ist outdated, right? :)

**Comment by tonimedina** [comment]
I will create a new PR for this using an up to date copy of the master branch, because there is too many merge conflicts.

**Pull request closed without merging**
